apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260625-210233-gr4jifadfp67-service
spec:
  selector:
    app: enterprise-system-20260625-210233-gr4jifadfp67
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
